## This help screen
help:
	@printf "Available targets:\n\n"
	@awk '/^[a-zA-Z\-\_0-9%:\\]+/ { \
          helpMessage = match(lastLine, /^## (.*)/); \
          if (helpMessage) { \
            helpCommand = $$1; \
            helpMessage = substr(lastLine, RSTART + 3, RLENGTH); \
      gsub("\\\\", "", helpCommand); \
      gsub(":+$$", "", helpCommand); \
            printf "  \x1b[32;01m%-35s\x1b[0m %s\n", helpCommand, helpMessage; \
          } \
        } \
        { lastLine = $$0 }' $(MAKEFILE_LIST) | sort -u
	@printf "\n"

## Build indexer docker image
docker/build:
	docker build -f ./infrastructure/Dockerfile ./../ -t btc_indexer:image

## Format code
fmt:
	cargo +nightly fmt --all

## Cleans whole directory from temporary files
clean:
	cargo clean --manifest-path $(CORE_CARGO_TOML)