//! # Spark Types Protobuf Definitions

//!

//! These are used to connect and make requests to Spark Operators.

//!

//! This module contains the generated code for the Spark Types.

//! It is generated by the build.rs script.

/// This module contains the generated code for the Spark Types.

#[allow(missing_docs)]
#[allow(clippy::all)]
#[allow(missing_docs)]
// Re-export prost to ensure it's available for the generated code
pub use prost;

/// The core for Spark proto types and service definitions. This module contains `spark.proto` and `spark_tree.proto` files.

pub mod common {
    include!(concat!(env!("OUT_DIR"), "/common.rs"));
}

/// This module contains the generated code for the Spark Operator RPC.
pub mod spark {
    include!(concat!(env!("OUT_DIR"), "/spark.rs"));
}

/// This module contains the generated code for the Spark Operator RPC.
pub mod spark_token {
    include!(concat!(env!("OUT_DIR"), "/spark_token.rs"));
}

/// This module contains the generated code for the Spark Operator RPC.
pub mod spark_tree {
    include!(concat!(env!("OUT_DIR"), "/spark_tree.rs"));
}

/// This module contains the generated code for the Spark Operator RPC.
pub mod frost {
    include!(concat!(env!("OUT_DIR"), "/frost.rs"));
}

/// This module contains the generated code for the Spark Operator RPC.
pub mod spark_authn {
    include!(concat!(env!("OUT_DIR"), "/spark_authn.rs"));
}
