/*!
 * This module re-exports the generated code for the Spark Operator RPC.
 * It is generated by the build.rs script.
 */

/// This module contains the generated code for the Spark Operator RPC.
pub mod spark_protos {
    /// This module contains the generated code for the Spark Operator RPC.
    pub mod common {
        include!(concat!(env!("OUT_DIR"), "/common.rs"));
    }

    /// This module contains the generated code for the Spark Operator RPC.
    pub mod spark {
        include!(concat!(env!("OUT_DIR"), "/spark.rs"));
    }

    /// This module contains the generated code for the Spark Operator RPC.
    pub mod spark_tree {
        include!(concat!(env!("OUT_DIR"), "/spark_tree.rs"));
    }

    /// This module contains the generated code for the Spark Operator RPC.
    pub mod spark_frost {
        include!(concat!(env!("OUT_DIR"), "/spark_frost.rs"));
    }

    /// This module contains the generated code for the Spark Operator RPC.
    pub mod spark_authn {
        include!(concat!(env!("OUT_DIR"), "/spark_authn.rs"));
    }
}

pub use spark_protos::*;
