@startuml

title Distributed Key Generation(DKG) flow (Generation of multisig public key via FROST scheme)

note over User,Aggregator:Initial call to perform **Dkg**

User->Aggregator: sends **key(s)** for unique mapping \n of stored on DB generated pubkeys

note over Aggregator,Verifier_1:Initial call to perform **DKG_round1** \n (generation of collective random values)
Aggregator->Verifier_1: request to get **DKG_round1** packages
Aggregator->Verifier_...: request to get **DKG_round1** packages
Aggregator->Verifier_n: request to get **DKG_round1** packages

note over Aggregator,Verifier_1:Performing **DKG_round2** \n (generation of private key shares with each participant)
Aggregator->Verifier_1: request to get **DKG_round2** packages
Aggregator->Verifier_...: request to get **DKG_round2** packages
Aggregator->Verifier_n: request to get **DKG_round2** packages

note over Aggregator,Verifier_1:Performing **DKG_finalize** \n (confirming and sharing of public verification share)
Aggregator->Verifier_1: request to get **DKG_finalize** packages
Aggregator->Verifier_...: request to get **DKG_finalize** packages
Aggregator->Verifier_n: request to get **DKG_finalize** packages

note over Aggregator,User:After competing DKG session signing of **message** can be performed \n Signature creation on **message**
User->Aggregator: sends **message** to be signed

note over Aggregator,Verifier_1:Performing **SigningRound1** \n (collecting ephemeral nonces per signing session)
Aggregator->Verifier_1: request to get **SigningRound1** packages
Aggregator->Verifier_...: request to get **SigningRound1** packages
Aggregator->Verifier_n: request to get **SigningRound1** packages

note over Aggregator,Verifier_1:Performing **SigningRound2** \n (collecting shares and deriving the joint signature)
Aggregator->Verifier_1: request to get **SigningRound2** packages
Aggregator->Verifier_...: request to get **SigningRound2** packages
Aggregator->Verifier_n: request to get **SigningRound2** packages

note over Aggregator,User:Performing sign filalization
Aggregator->User: perform finalization of signature creation for **message**

@enduml