@startuml

title Bridge interaction scheme Spark -> Rune

note over User_Spark_wallet,SparkEntity:User token transfer
User_Spark_wallet->SparkEntity: Token transfer to bridge wallet.

note over Spark_indexer,Proxy:Transfer detection event
Spark_indexer->Proxy:Extract last tx with: \n Users Spark wallet pubkey +\n burning event + \n extract additional information from meta
Proxy->SparkEntity: Trigger burning for tokens with meta taken in previous step

note over Bridge_Spark_wallet,SparkEntity:Bridge token burning
Proxy->Spark_signer_1: sign partially burning event to Spark
Proxy->Spark_signer_2: sign partially burning event to Spark
Proxy->SparkEntity: Token holders burn tokens by \n destroying their associated metadata.

note over Proxy, BTC_node:Forming exit tx in BTC to \n exchange wRunes -> Runes
Proxy->BTC_signer_1: sign partially formed transaction to BTC
Proxy->BTC_signer_2: sign partially formed transaction to BTC
Proxy->BTC_node: Create Appropriate tx in BTC chain on established BTC node

note over User_BTC_wallet, BTC_node: Tokens acquisition
User_BTC_wallet<-BTC_node: Runes

@enduml