@startuml

title Bridge interaction scheme [Spark -> Rune]

note over User_Spark_wallet,Gateway:Initial call to bridge tokens
User_Spark_wallet->Gateway: get address to replenish with parameters: \n **user_pubkey**
Gateway->Verifiers: Run dkg flow if **user_pubkey** is absent \n and return **dkg_pubkey**
Gateway->User_Spark_wallet: Return **bridge_spark_address** generated \n from tweaked **dkg_pubkey** with **nonce**
User_Spark_wallet->Spark_Entity: Create and send transaction to **bridge_spark_address** with appropriate amount of tokens

note over Spark_Balance_Checker,Gateway:Transfer detection event
Gateway->Verifiers:Check **bridge_spark_address** for receiving tokens
Verifiers<->Spark_Balance_Checker:Check **bridge_spark_address** for replenishment
Verifiers->Gateway:Tokens on **bridge_spark_address** are received
Gateway->Spark_Entity: Trigger burning for tokens that we receive on **bridge_spark_address**

note over Gateway,BTC_network:Perform **Runes** UTXOs selection and transferring
Gateway->Verifiers: * create appropriate transaction(s) \n (selection of appropriate RuneStones UTXOs & transfer) \n * call to Verifiers to sign transfer transaction(s)
Gateway->BTC_network: mint and send **wRunes** tokens to **address_to_send_Runes** on Spark chain

note over User_BTC_wallet, BTC_network: Tokens acquisition
User_BTC_wallet<-BTC_network: **Runes**

@enduml